config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :search1_queries

  get 'search_queries/update_values' => 'search_queries#update_values'

  get 'search_queries/queries_list' => 'search_queries#queries_list'

  get 'search_queries/browse_repository' => 'search_queries#browse_repository'

  resources :search_queries
  resources :methodologies
  resources :dev_methods
  resources :research_methods
  resources :statuses
  resources :authors
  resources :articles
  resources :article_types
  resources :ratings
  resources :feedbacks
  resources :research_participants
  resources :roles
  resources :users
  resources :logs_admin
  root 'home#index'
  
  
  get    '/login',   to: 'home#login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get "users/new", as: "register"

  match ':controller(/:action(/:id))', :via => :get

  get "admin/new_user", as: "admin_new_user"

  get 'admin/article_view_moderator', as:"article_view"
  get 'admin_controller/article_view'
  get "admin/article_detail", as: "article_detail"

  get 'admin/add_dev_method'
  get 'admin/update_methodology'
  post 'admin/update_methodology'
  get 'admin/mail_send'
  get "admin/article_view/Moderator" , as: "article_view_moderator"
  get "admin/article_view_moderator" , as: "article_moderator_picked_up"
  get "admin/user_management" , as: "user_management"
  post "admin/addNewUser" => "admin#addNewUser", :as => :addNewUser
  post "admin/updateUser" => "admin#updateUser", :as => :updateUser
  get "admin/feedback" , as: "admin_feedback"
  post "admin/add_feedback" , as: "admin_add_feedback"
  get "admin/add_feedback_confirmation" , as: "admin_add_feedback_confirmation"
end

app/models/article.rb
class Article < ActiveRecord::Base

  # Trung - Define model associations
  has_many :articles_research_participants
  has_many :research_participants, through: :articles_research_participants
  has_many :ratings
  has_many :users, through: :ratings
  has_many :articles_authors
  has_many :authors, through: :articles_authors
  has_many :articles_research_methods
  has_many :research_methods, through: :articles_research_methods
  has_many :articles_dev_methods
  has_many :dev_methods, through: :articles_dev_methods
  has_many :articles_methodologies
  has_many :methodologies, through: :articles_methodologies
  has_many :search_result_details

  belongs_to :status, foreign_key: :status_id
  belongs_to :article_type, foreign_key: :type_id
  belongs_to :user, foreign_key: :user_id

  attr_accessor :authors

  scope :search_by, -> (key, operator, value) {
    case operator
      when 1 # contains
        arel_table[key].matches "%#{value}%"
      when 2 # does not contains
        arel_table[key].does_not_match "%#{value}%"
      when 3 # begins with
        arel_table[key].matches "#{value}%"
      when 4 # end with
        arel_table[key].matches "%#{value}"
      when 5 # is equal to
        arel_table[key].eq value
      when 6 # is less than
        arel_table[key].lt value
      when 7 # is less than or equal
        arel_table[key].lteq value
      when 8 # is more than
        arel_table[key].gt value
      when 9 # is more than or equal
        arel_table[key].gteq value
    end
  }

  # pavan primary search in the search page
  def self.search(search)
    if search
      search = search.strip
      # where(["title LIKE ?","%#{search}%"])
      where(arel_table[:title].matches "%#{search}%")
    else
      all
    end
  end
end

app/models/article_type.rb
class ArticleType < ActiveRecord::Base

  # Trung - Define model associations
  has_many :articles

end

app/controllers/articles_controller.rb
class ArticlesController < BaseController

#layout false
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new

  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
        @article_id=Article.last.id

        # tell the moderator mailer to send an email
       # HubMailer.new_article_email(@article_id).deliver_now

      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title)
    end
  end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="bib">
    <tr>
      <th><label><%= f.label :title %></label></th>
      <td><%= @article.title %></td>
      </tr>
    <tr>
      <th><label><%= f.label :journal %></label></th>
      <td>
        <%= @article.journal %><br>
      </td>
    </tr>
    <tr>
      <th><label><%= f.label :Year %></label></th>
      <td><%= @article.year %><br></td>
    </tr>
    <tr><th><label><%= f.label :month %></label></th>
          <td><%= @article.month %></td>
    </tr>
    <tr>
      <th><label><%= f.label :Volume %></label></th>
      <td><%= @article.volume %>
            <label>Issue&nbsp;<%= f.label :number %></label>
        <%= @article.number %>
        <label><%= f.label :pages %></label>
        <%= @article.pages %>
        </td>
    </tr>
            <tr>
      <th>
          <label>DOI</label>
      </th>
      <td>
        <%= @article.doi %><br>
      </td>
    </tr>
    <tr>
      </table>


<div class="form-style-5">
<form>
  <fieldset>
    <legend><span class="number">1</span> Research Design</legend>
    <label><%= f.label :research_questions %></label>
    <%= f.text_area :research_questions, "cols" => 40, "rows" => 5%><br>
    <label><%= f.label :research_metrics %></label>
    <%= f.text_field :research_metrics %><br>

    <div class="field">
      <label>Research Method</label>
      <ul id = "limheight">
        <% @research_methods.each do |research_method| %>
          <div class="checkbox">
            <label>
              <% @is_check = false %>
              <% @article.research_methods.each_slice(3) do | batch | %>
                <% batch.each do |article_research_method| %>
                  <% if article_research_method.name == research_method.name%>
                    <% @is_check = true%>
                    <% break %>
                  <% end %>
                <% end %>
              <% end %>
              <%= check_box_tag 'article[research_method_ids][]', research_method.id, @is_check%>
              <%= research_method.name %></li>
            </label>
          </div>
        <% end %>
        </ul>

      <label>Research Participant</label>
      <ul id = "limheight">
      <% @research_participants.each do |research_participant| %>
        <div class="checkbox">
          <label>
            <% @is_check = false %>
            <% @article.research_participants.each do |article_research_participant| %>
              <% if article_research_participant.name == research_participant.name%>
                <% @is_check = true%>
                <% break %>
              <% end %>
            <% end %>
            <%= check_box_tag 'article[research_participant_ids][]', research_participant.id, @is_check%>
            <%= research_participant.name %>
          </label>
        </div>
      <% end %>
    </ul>
  </fieldset>

  <fieldset>
    <legend><span class="number">2</span>Evidence Item</legend>
    <label><%= f.label :benefit %></label>
    <%= f.text_area :benefit, "cols" => 40, "rows" => 5%><br>
    <label><%= f.label :context %></label>
    <%= f.text_field :context, "cols" => 40, "rows" => 5%><br>
    <label><%= f.label :result %></label>
    <%= f.text_field :result, "cols" => 40, "rows" => 5%><br>
  </fieldset>

  <fieldset>
    <legend><span class="number">3</span>Method</legend>
      <ul id = "limheight">
        <% @dev_methods.each do |dev_method| %>
          <div class="checkbox">
            <label>
              <% @is_check = false %>
              <% @article.dev_methods.each do |article_dev_method| %>
                <% if article_dev_method.name == dev_method.name%>
                  <% @is_check = true%>
                  <% break %>
                <% end %>
              <% end %>
              <%= check_box_tag 'article[dev_method_ids][]', dev_method.id, @is_check%>
              <%= dev_method.name %>
            </label>
          </div>
        <% end %>
      </ul>
  </fieldset>


  <fieldset>
    <legend>
      <span class="number">4</span>Methodology
    </legend>
    <ul id = "limheight">
      <% @methodologies.each do |methodology| %>
        <div class="checkbox">
          <label>
            <% @is_check = false %>
            <% @article.methodologies.each do |article_methodology| %>
              <% if article_methodology.name == methodology.name%>
                <% @is_check = true%>
                <% break %>
              <% end %>
            <% end %>
            <%= check_box_tag 'article[methodology_ids][]', methodology.id, @is_check%>
            <%= methodology.name %>
          </label>
        </div>
      <% end %>
    </ul>
  </fieldset>

<%= hidden_field_tag('article[user_ids][]', "5") %>

</form>

  <% @article.status.name = "Analysis complete" %>
    <div class="actions button">
      <input type="submit" name="commit" value="Update Article" />
      <input type="submit" name="commit" value="Submit Article" />
      <a href="<%=articles_path %>" class="button">Back to All Articles</a>
    </div>

<% end %>
</div>







  </div>

app/views/articles/edit.html.erb
<head>
<style>
.button123 {
    text-align: center;
    font-style: normal;
   
    border: 1px solid #16a085;
    border-width: 1px 1px 3px;
    vertical-align: middle
    position: absolute;
    margin-left: auto;
    margin-right: auto;
}

.center {
    display: block;
    margin: 0 auto;
}

.button123:hover{
    background: #109177;

}
</style>
</head>
<h1><%= @article.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user_role.name == "Admin" %>
<h1 id="head">All Articles</h1>
<table id="hor-minimalist-a">
  <thead>
    <tr>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Number</th>
      <th>Month</th>
      <th>Pages</th>
      <th>Status</th>
      <th>Function</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>

      <tr>
        <td><%= article.title %></td>
        <td><%= article.journal %></td>
        <td><%= article.year %></td>
        <td><%= article.volume %></td>
        <td><%= article.number %></td>
        <td><%= article.month %></td>
        <td><%= article.pages %></td>
        <td><%= article.status.name%></td>
        <td>
          <%= link_to 'Show', article %>
          <%= link_to 'Edit', edit_article_path(article) %>
          <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>
<% end %>

<% if current_user_role.name == "Moderator" %>
<h1 id="head">Accepted</h1>
<table id="hor-minimalist-a">
  <thead>
    <tr>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Number</th>
      <th>Month</th>
      <th>Pages</th>
      <th>Status</th>
      <th>Function</th>
    </tr>
  </thead>


  <tbody>
    <% @articles.each do |article| %>
      <% if article.status.name == 'Accepted' %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.journal %></td>
          <td><%= article.year %></td>
          <td><%= article.volume %></td>
          <td><%= article.number %></td>
          <td><%= article.month %></td>
          <td><%= article.pages %></td>
          <td><%= article.status.name%></td>
          <td>
            <%= link_to 'Show', article %>
            <!--<%= link_to 'Edit', edit_article_path(article) %>-->
            <!--<%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>-->
          </td>
        </tr>
      <% end %>

    <% end %>
  </tbody>
</table>

<h1 id="head">Rejected</h1>
<table id="hor-minimalist-a">
  <thead>
    <tr>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Number</th>
      <th>Month</th>
      <th>Pages</th>
      <th>Status</th>
      <th>Function</th>
    </tr>
  </thead>


  <tbody>
    <% @articles.each do |article| %>
      <% if article.status.name == 'Rejected' %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.journal %></td>
          <td><%= article.year %></td>
          <td><%= article.volume %></td>
          <td><%= article.number %></td>
          <td><%= article.month %></td>
          <td><%= article.pages %></td>
          <td><%= article.status.name%></td>
          <td>
            <%= link_to 'Show', article %>
            <!--<%= link_to 'Edit', edit_article_path(article) %>-->
            <!--<%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>-->
          </td>
        </tr>
      <% end %>

    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user_role.name == "Analyst" %>
<h1 id="head">To be Analysed</h1>
<table id="hor-minimalist-a">
  <thead>
    <tr>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Number</th>
      <th>Month</th>
      <th>Pages</th>
      <th>Status</th>
      <th>Function</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <% if article.status.name == 'To be analysed' %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.journal %></td>
        <td><%= article.year %></td>
        <td><%= article.volume %></td>
        <td><%= article.number %></td>
        <td><%= article.month %></td>
        <td><%= article.pages %></td>
        <td><%= article.status.name%>
        </td>
        <!--td><%= link_to 'Show', article %></td-->
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <!--td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h1 id="head">Partially Analysed</h1>
<table id="hor-minimalist-a">
  <thead>
    <tr>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Number</th>
      <th>Month</th>
      <th>Pages</th>
      <th>Status</th>
      <th>Function</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <% if article.status.name == 'Analyst picked up' %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.journal %></td>
        <td><%= article.year %></td>
        <td><%= article.volume %></td>
        <td><%= article.number %></td>
        <td><%= article.month %></td>
        <td><%= article.pages %></td>
        <td><%= article.status.name%>
        </td>
        <!--td><%= link_to 'Show', article %></td-->
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <!--td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h1 id="head">Completed</h1>
<table id="hor-minimalist-a">
  <thead>
    <tr>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Number</th>
      <th>Month</th>
      <th>Pages</th>
      <th>Status</th>

    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <% if article.status.name == 'Analysis complete' %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.journal %></td>
        <td><%= article.year %></td>
        <td><%= article.volume %></td>
        <td><%= article.number %></td>
        <td><%= article.month %></td>
        <td><%= article.pages %></td>
        <td><%= article.status.name%>
        </td>
        <!--td><%= link_to 'Show', article %></td-->
        <!--<td><%= link_to 'Edit', edit_article_path(article) %></td>-->
        <!--td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="form-style-5">
<form>
<fieldset>
<legend><span class="number">1</span>Title</legend>
        <%= f.text_area :title, "cols" => 40, "rows" => 5%>
</fieldset>

<fieldset>
<legend><span class="number">2</span>Source</legend>

      <div>
        <label>
          <%= select("article", "type_id", ArticleType.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Article Type'}) %>
        </label>
      </div>
        <%= f.text_field :journal, :placeholder => 'Book/Conference/Journal'%>
        <ul>
            <li>
                <%= f.text_field :volume, :placeholder => 'Volume'%>
            </li>
            <li>
                <%= f.text_field :number, :placeholder => 'Issue Number'%>       
            </li>
            <li>
                <%= f.text_field :pages, :placeholder => 'Pages'%>
            </li>
            <li>
                <%= select_month(Date.today, {}, name: 'article[month]') %>
            </li>
            <li><%= select_year(Date.today, {}, name: 'article[year]', start_year: 1950, end_year: 2016) %>
            </li>
        </ul>
        <ul>
            <li>
                <%= f.text_field :isbn, :placeholder => 'ISBN'%>
            </li>
            <li>
                <%= f.text_field :doi, :placeholder => 'DOI Number'%>       
            </li>
            <li>
                <%= f.text_field :url, :placeholder => 'URL'%>
            </li>
        </ul>
</fieldset>
<fieldset>
<legend><span class="number">3</span>Keywords</legend>
        <%= f.text_area :keyword, "cols" => 40, "rows" => 5, :placeholder => 'Separate using ;'%>
</fieldset>

<fieldset>
<legend><span class="number">4</span>Abstract</legend>
        <%= f.text_area :abstract, "cols" => 40, "rows" => 5%>
</fieldset>

</form>

 <div class="actions button">
   <ul>
            <li>
           <input type="submit" name="commit" value="Create Article" />
           </li>
           <li>
           <a href="<%=articles_path %>" class="button">Back to All Articles</a>
    </li>
  </div>
  
<% end %>
</div>
  </div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@article) do |f| %>
<h1>The following was successfully updated</h1>
<table class="bib">
    <tr>
      <th><label><%= f.label :title %></label></th>
      <td><%= @article.title %></td>
    </tr>
    <tr>
      <th><label><%= f.label :journal %></label></th>
      <td>
        <%= @article.journal %><br>
      </td>
    </tr>
    <tr>
      <th><label><%= f.label :Year %></label></th>
      <td><%= @article.year %><br></td>
    </tr>
    <tr>
      <th><label><%= f.label :month %></label></th>
      <td><%= @article.month %></td>
    </tr>
    <tr>
      <th><label><%= f.label :Volume %></label></th>
      <td><%= @article.volume %>
            <label style="padding-left:5em">Issue&nbsp;<%= f.label :number %></label>
        <%= @article.number %>
        <label style="padding-left:5em"><%= f.label :pages %></label>
        <%= @article.pages %>
      </td>
    </tr>
    <tr>
      <th>
          <label>DOI</label>
      </th>
      <td>
        <%= @article.doi %><br>
      </td>
    </tr>
        <tr>
      <th>
          <label>Research Questions</label>
      </th>
      <td><%= @article.research_questions %></td>
    </tr>
    <tr>
      <th>
          <label>Research Metrics</label>
      </th>
      <td><%= @article.research_metrics %></td>
    </tr>
    <tr>
      <th>
          <label>Research Methods</label>
      </th>
      <% @article_research_method = ""%>
      <% @article.research_methods.each do |research_method| %>
        <% @article_research_method = @article_research_method + research_method.name + ", "%>
      <% end %>
      <td><%= @article_research_method.chop.chop %></td>
    </tr>
    <tr>
      <th>
          <label>Research Participants</label>
      </th>
      <% @article_research_participant = ""%>
      <% @article.research_participants.each do |research_participant| %>
        <% @article_research_participant = @article_research_participant + research_participant.name + ", "%>
      <% end %>
      <td><%= @article_research_participant.chop.chop %></td>
    </tr>
    
    <tr>
      <th>
          <label>Evidence Item-Benefit</label>
      </th>
      <td><%= @article.benefit %></td>
    </tr>
    
    <tr>
      <th>
          <label>Evidence Item-Context</label>
      </th>
      <td><%= @article.context %></td>
    </tr>
    
    <tr>
      <th>
          <label>Evidence Item-Result</label>
      </th>
      <td><%= @article.result %></td>
    </tr>
    
    <tr>
      <th>
          <label>Development Method</label>
      </th>
      <% @article_dev_method = ""%>
      <% @article.dev_methods.each do |dev_method| %>
        <% @article_dev_method = @article_dev_method + dev_method.name + ", "%>
      <% end %>
      <td><%= @article_dev_method.chop.chop %></td>
    </tr>
    
    <tr>
      <th>
          <label>Methodology</label>
      </th>
      <% @article_methodology = ""%>
      <% @article.methodologies.each do |methodology| %>
        <% @article_methodology = @article_methodology + methodology.name + ", "%>
      <% end %>
      <td><%= @article_methodology.chop.chop %></td>
    </tr>
    
</table>
<%end%>
<div class="form-style-5 actions button">
    <!--<a href="<%=edit_article_path(@article) %>" class="button">Re-Update</a>-->
    <a href="<%=articles_path %>" class="button">Back to All Articles</a>
    
  </div>