config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :search1_queries

  get 'search_queries/update_values' => 'search_queries#update_values'

  get 'search_queries/queries_list' => 'search_queries#queries_list'

  get 'search_queries/browse_repository' => 'search_queries#browse_repository'

  resources :search_queries
  resources :methodologies
  resources :dev_methods
  resources :research_methods
  resources :statuses
  resources :authors
  resources :articles
  resources :article_types
  resources :ratings
  resources :feedbacks
  resources :research_participants
  resources :roles
  resources :users
  resources :logs_admin
  root 'home#index'
  
  
  get    '/login',   to: 'home#login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get "users/new", as: "register"

  match ':controller(/:action(/:id))', :via => :get

  get "admin/new_user", as: "admin_new_user"

  get 'admin/article_view_moderator', as:"article_view"
  get 'admin_controller/article_view'
  get "admin/article_detail", as: "article_detail"

  get 'admin/add_dev_method'
  get 'admin/update_methodology'
  post 'admin/update_methodology'
  get 'admin/mail_send'
  get "admin/article_view/Moderator" , as: "article_view_moderator"
  get "admin/article_view_moderator" , as: "article_moderator_picked_up"
  get "admin/user_management" , as: "user_management"
  post "admin/addNewUser" => "admin#addNewUser", :as => :addNewUser
  post "admin/updateUser" => "admin#updateUser", :as => :updateUser
  get "admin/feedback" , as: "admin_feedback"
  post "admin/add_feedback" , as: "admin_add_feedback"
  get "admin/add_feedback_confirmation" , as: "admin_add_feedback_confirmation"
end

app/models/research_method.rb
class ResearchMethod < ActiveRecord::Base

  # Trung - Define model associations
  has_many :articles_research_methods
  has_many :articles, through: :articles_research_methods

  scope :search_by, -> (key, operator, value) {
    case operator
      when 1 # contains
        arel_table[key].matches "%#{value}%"
      when 2 # does not contains
        arel_table[key].does_not_match "%#{value}%"
      when 3 # begins with
        arel_table[key].matches "#{value}%"
      when 4 # end with
        arel_table[key].matches "%#{value}"
      when 5 # is equal to
        arel_table[key].eq value
      when 6 # is less than
        arel_table[key].lt value
      when 7 # is less than or equal
        arel_table[key].lteq value
      when 8 # is more than
        arel_table[key].gt value
      when 9 # is more than or equal
        arel_table[key].gteq value
    end
  }

end

app/controllers/research_methods_controller.rb
class ResearchMethodsController < BaseController
  before_action :set_research_method, only: [:show, :edit, :update, :destroy]

  # GET /research_methods
  # GET /research_methods.json
  def index
    @research_methods = ResearchMethod.all
  end

  # GET /research_methods/1
  # GET /research_methods/1.json
  def show
  end

  # GET /research_methods/new
  def new
    @research_method = ResearchMethod.new
  end

  # GET /research_methods/1/edit
  def edit
  end

  # POST /research_methods
  # POST /research_methods.json
  def create
    @research_method = ResearchMethod.new(research_method_params)

    respond_to do |format|
      if @research_method.save
        format.html { redirect_to @research_method, notice: 'Research method was successfully created.' }
        format.json { render :show, status: :created, location: @research_method }
      else
        format.html { render :new }
        format.json { render json: @research_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /research_methods/1
  # PATCH/PUT /research_methods/1.json
  def update
    respond_to do |format|
      if @research_method.update(research_method_params)
        format.html { redirect_to @research_method, notice: 'Research method was successfully updated.' }
        format.json { render :show, status: :ok, location: @research_method }
      else
        format.html { render :edit }
        format.json { render json: @research_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /research_methods/1
  # DELETE /research_methods/1.json
  def destroy
    @research_method.destroy
    respond_to do |format|
      format.html { redirect_to research_methods_url, notice: 'Research method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_method
      @research_method = ResearchMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def research_method_params
      params.require(:research_method).permit(:name)
    end
end

app/helpers/research_methods_helper.rb
module ResearchMethodsHelper
end

app/views/research_methods/_form.html.erb
<%= form_for(@research_method) do |f| %>
  <% if @research_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@research_method.errors.count, "error") %> prohibited this research_method from being saved:</h2>

      <ul>
      <% @research_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/research_methods/edit.html.erb
<h1>Editing Research Method</h1>

<%= render 'form' %>

<%= link_to 'Show', @research_method %> |
<%= link_to 'Back', research_methods_path %>

app/views/research_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Research Methods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @research_methods.each do |research_method| %>
      <tr>
        <td><%= research_method.name %></td>
        <td><%= link_to 'Show', research_method %></td>
        <td><%= link_to 'Edit', edit_research_method_path(research_method) %></td>
        <td><%= link_to 'Destroy', research_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Research method', new_research_method_path %>

app/views/research_methods/new.html.erb
<h1>New Research Method</h1>

<%= render 'form' %>

<%= link_to 'Back', research_methods_path %>

app/views/research_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @research_method.name %>
</p>

<%= link_to 'Edit', edit_research_method_path(@research_method) %> |
<%= link_to 'Back', research_methods_path %>