config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :search1_queries

  get 'search_queries/update_values' => 'search_queries#update_values'

  get 'search_queries/queries_list' => 'search_queries#queries_list'

  get 'search_queries/browse_repository' => 'search_queries#browse_repository'

  resources :search_queries
  resources :methodologies
  resources :dev_methods
  resources :research_methods
  resources :statuses
  resources :authors
  resources :articles
  resources :article_types
  resources :ratings
  resources :feedbacks
  resources :research_participants
  resources :roles
  resources :users
  resources :logs_admin
  root 'home#index'
  
  
  get    '/login',   to: 'home#login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get "users/new", as: "register"

  match ':controller(/:action(/:id))', :via => :get

  get "admin/new_user", as: "admin_new_user"

  get 'admin/article_view_moderator', as:"article_view"
  get 'admin_controller/article_view'
  get "admin/article_detail", as: "article_detail"

  get 'admin/add_dev_method'
  get 'admin/update_methodology'
  post 'admin/update_methodology'
  get 'admin/mail_send'
  get "admin/article_view/Moderator" , as: "article_view_moderator"
  get "admin/article_view_moderator" , as: "article_moderator_picked_up"
  get "admin/user_management" , as: "user_management"
  post "admin/addNewUser" => "admin#addNewUser", :as => :addNewUser
  post "admin/updateUser" => "admin#updateUser", :as => :updateUser
  get "admin/feedback" , as: "admin_feedback"
  post "admin/add_feedback" , as: "admin_add_feedback"
  get "admin/add_feedback_confirmation" , as: "admin_add_feedback_confirmation"
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  # Trung - Define model associations
  belongs_to :user, foreign_key: :user_id
  belongs_to :article, foreign_key: :article_id

end

app/controllers/ratings_controller.rb
class RatingsController < BaseController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:value)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.value %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @rating.value %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>