config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :search1_queries

  get 'search_queries/update_values' => 'search_queries#update_values'

  get 'search_queries/queries_list' => 'search_queries#queries_list'

  get 'search_queries/browse_repository' => 'search_queries#browse_repository'

  resources :search_queries
  resources :methodologies
  resources :dev_methods
  resources :research_methods
  resources :statuses
  resources :authors
  resources :articles
  resources :article_types
  resources :ratings
  resources :feedbacks
  resources :research_participants
  resources :roles
  resources :users
  resources :logs_admin
  root 'home#index'
  
  
  get    '/login',   to: 'home#login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get "users/new", as: "register"

  match ':controller(/:action(/:id))', :via => :get

  get "admin/new_user", as: "admin_new_user"

  get 'admin/article_view_moderator', as:"article_view"
  get 'admin_controller/article_view'
  get "admin/article_detail", as: "article_detail"

  get 'admin/add_dev_method'
  get 'admin/update_methodology'
  post 'admin/update_methodology'
  get 'admin/mail_send'
  get "admin/article_view/Moderator" , as: "article_view_moderator"
  get "admin/article_view_moderator" , as: "article_moderator_picked_up"
  get "admin/user_management" , as: "user_management"
  post "admin/addNewUser" => "admin#addNewUser", :as => :addNewUser
  post "admin/updateUser" => "admin#updateUser", :as => :updateUser
  get "admin/feedback" , as: "admin_feedback"
  post "admin/add_feedback" , as: "admin_add_feedback"
  get "admin/add_feedback_confirmation" , as: "admin_add_feedback_confirmation"
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

  # Trung - Define model associations
  belongs_to :user, foreign_key: :user_id

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < BaseController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:user_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.user_id %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>